# Basic usage of the ``h5pywrappers`` library #

## A NOTE BEFORE STARTING ##

Since the ``h5pywrappers`` git repository tracks this notebook under its
original basename ``basic_usage.ipynb``, we recommend that you copy the original
notebook and rename it to any other basename that is not one of the original
basenames that appear in the ``<root>/examples`` directory before executing any
of the notebook cells below, where ``<root>`` is the root of the
``h5pywrappers`` repository. This way you can explore the notebook by executing
and modifying cells without changing the original notebook, which is being
tracked by git.

## Import necessary modules ##

In [1]:
# For general array handling and constructing random number generators.
import numpy as np

import h5py



# The library that is the subject of this demonstration.
import h5pywrappers

## Introduction ##

In this notebook, we demonstrate how one can use each function and class in the
``h5pywrappers`` library.

You can find the documentation for the ``h5pywrappers`` library
[here](https://mrfitzpa.github.io/h5pywrappers/_build/html/_autosummary/h5pywrappers.html).
It is recommended that you consult the documentation of this library as you
explore the notebook. Moreover, users should execute the cells in the order that
they appear, i.e. from top to bottom, as some cells reference variables that are
set in other cells above them.

## Using the ``h5pywrappers`` function ##

Insert text here.

In [2]:
filename = "bar.h5"
path_in_file = "group-2-C"
group_id = h5pywrappers.obj.ID(filename, path_in_file)

In [3]:
group = h5pywrappers.group.load(group_id, read_only=True)

In [4]:
group.file.keys()

<KeysViewHDF5 ['group-2-C']>

In [5]:
group.file.close()

In [6]:
filename = "bar.h5"
path_in_file = "group-2-D"
group_id = h5pywrappers.obj.ID(filename, path_in_file)

In [7]:
h5pywrappers.group.save(None, group_id, write_mode="a")

TypeError: isinstance() arg 2 must be a type or tuple of types

In [35]:
h5py.Dataset

h5py._hl.dataset.Dataset

In [32]:
h5pywrappers.file.generator_1("foo.h5", overwrite=True)
h5pywrappers.file.generator_2("bar.h5", overwrite=True)

In [3]:
filename = "foo.h5"
path_in_file = "group-1-A/dataset-1-A"
dataset_id = h5pywrappers.obj.ID(filename, path_in_file)

In [4]:
dataset = h5pywrappers.dataset.load(dataset_id, read_only=True)

In [5]:
dataset

<HDF5 dataset "dataset-1-A": shape (12, 9, 128, 150), type "<f8">

In [6]:
dataset.file.close()

In [7]:
multi_dim_slice = (0, slice(None, None, -2), [120, -50], 5)

In [8]:
datasubset_id = h5pywrappers.datasubset.ID(dataset_id, 
                                           multi_dim_slice)

In [30]:
datasubset = h5pywrappers.datasubset.load(datasubset_id)

In [31]:
datasubset

array([[0.28919873, 0.56922889],
       [0.34056206, 0.56448673],
       [0.96827591, 0.34958929],
       [0.69597617, 0.82573635],
       [0.6956494 , 0.92554344]])

In [20]:
dataset = h5pywrappers.dataset.load(dataset_id, read_only=True)

In [21]:
dataset[(0, slice(None, None, 2), [2, 125], 5)]

array([[0.74632253, 0.70194711],
       [0.38910626, 0.12371782],
       [0.85950058, 0.83769564],
       [0.5411634 , 0.92919001],
       [0.01421658, 0.55301119]])

In [22]:
dataset.file.close()

In [27]:
test_shape = datasubset.shape
test = np.random.rand(*test_shape)

In [28]:
test

array([[0.28919873, 0.56922889],
       [0.34056206, 0.56448673],
       [0.96827591, 0.34958929],
       [0.69597617, 0.82573635],
       [0.6956494 , 0.92554344]])

In [29]:
h5pywrappers.datasubset.save(test, datasubset_id)

In [40]:
filename = "foo.h5"
path_in_file = "group-1-A/test-dataset"
obj_id = h5pywrappers.obj.ID(filename, path_in_file)

obj = h5pywrappers.obj.load(obj_id, read_only=True)

In [43]:
obj.file.close()

In [42]:
obj[3] = -10

OSError: Can't write data (no write intent on file)

In [56]:
filename = "bar.h5"
path_in_file = "group-2-A/dataset-2-A"
dataset_id = h5pywrappers.obj.ID(filename, path_in_file)

In [57]:
dataset = h5pywrappers.dataset.load(dataset_id, read_only=False)

In [58]:
dataset[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(10).dtype

dtype('int64')

In [45]:
test = np.random.rand(3, 4, 2)

In [48]:
test.flat[0].astype(dataset.dtype)

0

In [34]:
test.flat[0]

0.633329018184781

In [59]:
dataset.dtype

dtype('int64')

In [69]:
(1.2j*np.arange(3)).dtype

dtype('complex128')

In [70]:
IOError("Hello world")

OSError('Hello world')

In [71]:
try:
    1/0
except:
    raise IOError("Hello world")

OSError: Hello world

In [66]:
dataset[:3] = 1.2j*np.arange(3)

ValueError: Cannot return member number (operation not supported for type class)

Exception ignored in: 'h5py._proxy.make_reduced_type'
Traceback (most recent call last):
  File "/home/matthew/anaconda3/envs/emicro/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 982, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
ValueError: Cannot return member number (operation not supported for type class)


ValueError: Not a datatype (not a datatype)

In [64]:
dataset[:]

array([0, 1, 2, 7, 4, 5, 6, 7, 8, 9])

In [61]:
dataset[0, 0, 0, :10]

ValueError: 4 indexing arguments for 1 dimensions

In [55]:
dataset.file.close()

In [111]:
file_obj = h5py.File("foo.h5", "r")

In [112]:
file_obj.keys()

<KeysViewHDF5 ['group-1-A']>

In [113]:
file_obj['group-1-A'].keys()

<KeysViewHDF5 ['dataset-1-B']>

In [114]:
file_obj.close()

In [101]:
filename = "foo.h5"
path_in_file = "group-1-A/dataset-1-B"
dataset_id_1 = h5pywrappers.obj.ID(filename, path_in_file)

filename = "bar.h5"
path_in_file = "group-2-A/dataset-2-A"
dataset_id_2 = h5pywrappers.obj.ID(filename, path_in_file)

In [102]:
dataset_2 = h5pywrappers.dataset.load(dataset_id_2, read_only=True)

In [103]:
dataset_2[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
dataset_2.file.close()

ValueError: Not an id of a file object (not an ID of a file object)

In [109]:
h5pywrappers.dataset.save(dataset_2, dataset_id_1, write_mode="w")

In [29]:
obj.create_dataset("test-dataset", data=np.arange(5, 15))

<HDF5 dataset "test-dataset": shape (10,), type "<i8">

In [30]:
obj.file.close()

In [ ]:
filename = "foo.h5"
path_in_file = "group-1-A"
obj_id = h5pywrappers.obj.ID(filename, path_in_file)

obj = h5pywrappers.obj.load(obj_id, read_only=False)

In [ ]:
filename = "foo.h5"
path_in_file = "group-1-A/dataset-1-A"
with h5py.File(filename, "a") as file_obj_2:
    dataset = file_obj_2[path_in_file]
    print(dataset.dtype)

In [2]:
# Insert code here.

In [2]:
h5pywrappers.file.generator_1("foo.h5", overwrite=True)

In [3]:
filename = "foo.h5"
path_in_file = "group-1-A"
obj_id = h5pywrappers.obj.ID(filename, path_in_file)

In [4]:
obj = h5pywrappers.obj.load(obj_id)

In [5]:
obj.keys()

<KeysViewHDF5 ['dataset-1-A', 'scalar-1-A']>

In [6]:
obj['scalar-1-A']

<HDF5 dataset "scalar-1-A": shape (), type "<f8">

In [7]:
obj.file.close()

In [9]:
obj

<Closed HDF5 group>

In [126]:
filename = "bar.h5"
path_in_file = "group-2-A/scalar-2-A"
scalar_id = h5pywrappers.obj.ID(filename, path_in_file)

In [127]:
scalar = h5pywrappers.scalar.load(scalar_id)

In [128]:
scalar

0.5j

In [13]:
filename = "foo.h5"
path_in_file = "group-1-A/dataset-1-A"
dataset_id = h5pywrappers.obj.ID(filename, path_in_file)

In [14]:
dataset = h5pywrappers.dataset.load(dataset_id)

In [15]:
dataset

<HDF5 dataset "dataset-1-A": shape (12, 9, 128, 150), type "<f8">

In [16]:
dataset.dtype

dtype('<f8')

In [17]:
dataset.file.close()

In [18]:
dataset

<Closed HDF5 dataset>

In [19]:
filename = "foo.h5"
path_in_file = "group-1-A/dataset-1-A"
file_obj_1 = h5py.File(filename, "a")
file_obj_2 = h5py.File(filename, "r")

In [20]:
file_obj_1.close()

In [21]:
file_obj_1

<Closed HDF5 file>

In [22]:
file_obj_2

<HDF5 file "foo.h5" (mode r+)>

In [6]:
filename = "foo.h5"
path_in_file = "group-1-A/dataset-1-A"
with h5py.File(filename, "a") as file_obj_2:
    dataset = file_obj_2[path_in_file]
    print(dataset.dtype)

float64


ValueError: could not convert string to float: 'd'

In [30]:
file_obj_1.close()
file_obj_2.close()

In [18]:
attr_name = "was_randomly_generated"
attr_id = h5pywrappers.attr.ID(obj_id=dataset_id, 
                               attr_name=attr_name)

In [15]:
attr = h5pywrappers.attr.load(attr_id)

In [16]:
attr

'False'

In [19]:
h5pywrappers.attr.save("True", attr_id, write_mode="a")

ValueError: No HDF5 object was found at the HDF5 path ``'group-1-A/dataset-1-B'`` of the HDF5 file at the file path``'foo.h5'``.

In [22]:
filename = "foo.h5"
path_in_file = "group-1-B/json-document-1-B"
json_document_id = h5pywrappers.obj.ID(filename, path_in_file)

In [23]:
json_document = h5pywrappers.json.document.load(json_document_id)

In [24]:
json_document

{'a': 1, 'b': 2, 'c': 3}